config/routes.rb
Rails.application.routes.draw do
  root 'pages#kitchensink'
  
  resources :tweets
  devise_for :users
  
  get 'multiple_select', to: 'pages#multiple_select'
  get 'online_users', to: 'pages#online_users'
  get 'modal', to: 'pages#modal'
  get 'landing_page', to: 'pages#landing_page'
  post 'track_event', to: 'pages#track_event'
  
  resources :technologies, only: [:create]
  resources :favourite_technologies, only: [:create, :destroy]

  resources :recipes, except: [:destroy]
  resources :ingredients, only: [:destroy]
  resources :nested_ingredients, only: [:new, :destroy]
  resources :characters, only: [:index, :destroy]

  resources :chatrooms, only: [:index, :show] do 
    resources :messages, only: [:create]
  end

  resources :tic_tac_toe_games, only: [:index, :show, :create] do
    resources :tic_tac_toe_moves, only: [:create], as: :moves
  end

  namespace :onboarding do
    resources :developer_informations, only: %i[new create]
    resources :developer_skills, only: %i[new create]
    resources :developer_preferences, only: %i[new create]
  end

  resources :developers, only: %i[show]
  resources :commands, only: %i[index]
  resources :places, only: %i[index create]
  resources :todos, only: %i[index update]
  resources :coffee_prompts, only: %i[new create]

  get 'tabs', to: 'pages#tabs'
  get 'profile_tab', to: 'pages#profile_tab'
  get 'personal_info_tab', to: 'pages#personal_info_tab'
  get 'notifications_tab', to: 'pages#notifications_tab'

  resources :posts, only: %i[new create edit update show]
  resources :slow_characters, only: %i[index]

  resources :profiles, only: %i[index]

  resources :pizzas, only: %i[index]
  resources :toppings, only: %i[index]

  resources :kanban_boards, only: %i[show]
  resources :kanban_columns, only: %i[update]
  resources :kanban_cards, only: %i[update]
  
  resources :users, only: %i[show]
  resources :follows, only: %i[create]
  
  resources :emails, only: %i[index]
  namespace :emails do
    resource :bulk, only: :destroy, controller: :bulk
  end

  resources :comments, only: %i[index new create show] do
    resources :replies, only: %i[new create]
  end

  resources :events, only: %i[index new create]
  resources :pets, only: %i[new create index]
end

app/models/character.rb
class Character < ApplicationRecord
  scope :by_name, -> (name) { where('name ILIKE ?', "%#{name}%") }
  scope :by_species, -> (species) { where species: species }
  scope :by_homeworld, -> (homeworld) { where homeworld: homeworld }
  scope :by_affiliation, -> (affiliation) { where affiliation: affiliation }

  def self.search(params)
    characters = where(nil)

    characters = characters.by_name(params[:name]) if params[:name].present?
    characters = characters.by_species(params[:species]) if params[:species].present?
    characters = characters.by_homeworld(params[:homeworlds]) if params[:homeworlds].present?
    characters = characters.by_affiliation(params[:affiliations]) if params[:affiliations].present?

    characters
  end
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/command.rb
class Command < ApplicationRecord
  scope :by_name, -> (query) { where("name LIKE ?", "%#{query}%") }

  def self.search(params)
    commands = where(nil)
    commands = commands.by_name(params[:query])
    commands
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :parent, class_name: "Comment", optional: true
  has_many :replies, foreign_key: "parent_id", class_name: "Comment", dependent: :destroy

  default_scope { order(created_at: :desc) }
  scope :top_level, -> { where(parent_id: nil) }
end

app/models/developer.rb
class Developer < ApplicationRecord
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  default_scope { order(starting_at: :asc) }
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :followed_user, class_name: 'User'
  belongs_to :follower, class_name: 'User'

  after_create_commit :send_notification

  private

  def send_notification
    NewFollowerNotification.with(follow: self).deliver_later(followed_user)
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :specializations

  accepts_nested_attributes_for :specializations, allow_destroy: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  has_rich_text :content

  after_create_commit {
    broadcast_append_to "chatroom_#{chatroom.id}",
      target: "messages",
      partial: 'messages/message'
  }
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_one_attached :photo
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  has_many :pizza_toppings
  has_many :toppings, through: :pizza_toppings

  def topping_names
    toppings.map(&:name).join(', ').titleize
  end
end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def as_marker
    { lat: latitude, lng: longitude }
  end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :job
  belongs_to :specialization
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank
end

app/models/todo.rb
class Todo < ApplicationRecord
  scope :completed, -> { where(completed: true) }
  scope :incomplete, -> { where(completed: false) }
end

app/models/topping.rb
class Topping < ApplicationRecord
  has_many :pizza_toppings
  has_many :pizzas, through: :pizza_toppings

  scope :filter_by_name, -> (name) { where("name ILIKE ?", "%#{name}%") }

  def self.search(params)
    toppings = all
    toppings = toppings.filter_by_name(params[:name]) if params[:name].present?

    toppings
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :messages, dependent: :destroy
  has_many :tic_tac_toe_games, dependent: :destroy
  has_many :tic_tac_toe_moves, dependent: :destroy

  has_many :notifications, as: :recipient, dependent: :destroy

  has_many :followees, foreign_key: :follower_id, class_name: "Follow", dependent: :destroy
  has_many :followed_users, through: :followees

  has_many :following_users, foreign_key: :followed_user_id, class_name: "Follow", dependent: :destroy
  has_many :followers, through: :following_users

  def self.online
    ids = ActionCable.server.pubsub.redis_connection_for_subscriptions.smembers("online_users")
    where(id: ids)
  end

  def broadcast_online
    broadcast_append_to "online_users", target: "online_users",
      partial: 'users/card',
      locals: { user: self }
  end

  def broadcast_offline
    broadcast_remove_to "online_users", target: "user_#{id}"
  end
end

app/controllers/recipes/ingredients_controller.rb
module Recipes
  class IngredientsController < ApplicationController
    def destroy
      recipe = Recipe.find(params[:recipe_id])
      @ingredient = recipe.ingredients.find(params[:id])
      @ingredient.destroy
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new(ingredients: [Ingredient.new])
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to root_path, notice: "Recipe was successfully created."
    end
  end

  def index
    @recipes = Recipe.all
  end

  def edit
    @recipe = Recipe.includes(:ingredients).find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to root_path, notice: "Recipe was successfully created."
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, ingredients_attributes: [:id, :name, :_destroy])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with model: recipe do |form| %>
  <div class="shadow sm:overflow-hidden sm:rounded-md">
    <div class="space-y-6 bg-white px-4 py-5 sm:p-6">
      <div class="grid grid-cols-3 gap-6">
        <div class="col-span-3 sm:col-span-2">
          <%= form.label :name, class: "block text-sm font-medium text-gray-700" %>
          <div class="mt-1 flex rounded-md shadow-sm">
            <%= form.text_field :name, class: "block w-full flex-1 rounded-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", placeholder: "Carbonara" %>
          </div>
        </div>
      </div>


        <!-- Ingredients section-->
        <div class="relative">
          <div class="absolute inset-0 flex items-center" aria-hidden="true">
            <div class="w-full border-t border-gray-300"></div>
          </div>
          <div class="relative flex justify-start">
            <span class="bg-white pr-2 text-sm text-gray-500">Ingredients</span>
          </div>
        </div>

        <!-- Ingredients list-->
        <div id="ingredients" class="space-y-3" data-template-manager-target="container">
          <%= form.fields_for :ingredients do |ingredients_form| %>
            <%= render "ingredient_fields", form: ingredients_form, recipe: recipe %>
          <% end %>
        </div>

        <!-- Ingredients: Add new-->
        <div class="relative">
          <div class="absolute inset-0 flex items-center" aria-hidden="true">
            <div class="w-full border-t border-gray-300"></div>
          </div>
          <div class="relative flex justify-center">
            <button type="button"
                    class="bg-white px-2 text-gray-500"
                    data-controller="turbo-stream-button"
                    data-action="turbo-stream-button#evaluate">
              <svg class="h-5 w-5 text-gray-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
              </svg>
              <!-- Ingredients template-->
              <template data-turbo-stream-button-target="turboStreams">
                <%= form.fields_for "ingredients_attributes", index: "replace_with_epoch" do |template_form| %>
                  <%= render "template_field", form: template_form %>
                <% end %>
              </template>
            </button>
          </div>
        </div>

    </div>
    <div class="bg-gray-50 px-4 py-3 text-right sm:px-6">
      <button type="submit" class="inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Save</button>
    </div>
  </div>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div id="<%= dom_id(form.object) %>" data-controller="visibility"
     class="grid grid-cols-3 gap-6">
  <div class="col-span-3">
    <div class="flex rounded-md shadow-sm relative">
      <%= form.text_field :name, class: "block w-full flex-1 rounded-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", placeholder: "Eggs" %>

      <% if form.object.persisted? %>
        <%= link_to recipe_ingredient_path(recipe, form.object),
                    data: {
                      turbo_method: :delete
                    } do %>
          <span class="bg-red-100 absolute w-10 border border-gray-300 rounded-r-md right-0 top-0 bottom-0 flex items-center justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
            </svg>
          </span>
        <% end %>
      <% else %>
        <button data-action="visibility#remove" type="button" class="bg-red-100 absolute w-10 border border-gray-300 rounded-r-md right-0 top-0 bottom-0 flex items-center justify-center">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
          </svg>
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/_template_field.html.erb
<%= turbo_stream.append "ingredients" do  %>
  <div data-controller="dynamic-form-field visibility"
       data-dynamic-form-field-index-value="<%= form.index %>"
       class="grid grid-cols-3 gap-6">
    <div class="col-span-3">
      <div class="flex rounded-md shadow-sm relative">
        <%= form.text_field :name,
                            class: "block w-full flex-1 rounded-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm",
                            placeholder: "Eggs",
                            data: {
                              dynamic_form_field_target: "field"
                            } %>
        <button data-action="visibility#remove"
                type="button"
                class="bg-red-100 absolute w-10 border border-gray-300 rounded-r-md right-0 top-0 bottom-0 flex items-center justify-center">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
          </svg>
        </button>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="mx-auto bg-gray-100 p-10 my-20 rounded-lg">
  <div>
    <div class="md:grid md:grid-cols-3 md:gap-6">
      <div class="md:col-span-1">
        <div class="px-4 sm:px-0">
          <h3 class="text-base font-semibold leading-6 text-gray-900">Edit your <%= @recipe.name %> recipe 👩‍🍳</h3>
          <p class="mt-1 text-sm text-gray-600">This information will be displayed publicly so be careful what you share.</p>
        </div>
      </div>
      <div class="mt-5 md:col-span-2 md:mt-0">
        <%= render 'form', recipe: @recipe %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<%= turbo_frame_tag "recipes_table", class: "w-full" do %>
  <div class="px-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-base font-semibold leading-6 text-gray-900">Recipes 👩‍🍳</h1>
        <p class="mt-2 text-sm text-gray-700">A list of all your tasty recipes.</p>
      </div>
      <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
        <%= link_to "Add Recipe", new_recipe_path, class: "block rounded-md bg-indigo-600 py-1.5 px-3 text-center text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", data: { turbo_frame: "_top" } %>
      </div>
    </div>
    <div class="mt-8 flow-root">
      <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
          <table class="min-w-full divide-y divide-gray-300">
            <thead>
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Name</th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                  <span class="sr-only">Add Recipe</span>
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200">
              <% @recipes.each do |recipe| %>
                <tr>
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= recipe.name %></td>
                  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                    <%= link_to "Edit", edit_recipe_path(recipe), class: "text-indigo-600 hover:text-indigo-900" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<div class="mx-auto bg-gray-100 p-10 my-20 rounded-lg">
  <div>
    <div class="md:grid md:grid-cols-3 md:gap-6">
      <div class="md:col-span-1">
        <div class="px-4 sm:px-0">
          <h3 class="text-base font-semibold leading-6 text-gray-900">Add a new recipe 👩‍🍳</h3>
          <p class="mt-1 text-sm text-gray-600">This information will be displayed publicly so be careful what you share.</p>
        </div>
      </div>
      <div class="mt-5 md:col-span-2 md:mt-0">
        <%= render 'form', recipe: @recipe %>
      </div>
    </div>
  </div>
</div>