config/routes.rb
Rails.application.routes.draw do
  root 'pages#kitchensink'
  
  resources :tweets
  devise_for :users
  
  get 'multiple_select', to: 'pages#multiple_select'
  get 'online_users', to: 'pages#online_users'
  get 'modal', to: 'pages#modal'
  get 'landing_page', to: 'pages#landing_page'
  post 'track_event', to: 'pages#track_event'
  
  resources :technologies, only: [:create]
  resources :favourite_technologies, only: [:create, :destroy]

  resources :recipes, except: [:destroy]
  resources :ingredients, only: [:destroy]
  resources :nested_ingredients, only: [:new, :destroy]
  resources :characters, only: [:index, :destroy]

  resources :chatrooms, only: [:index, :show] do 
    resources :messages, only: [:create]
  end

  resources :tic_tac_toe_games, only: [:index, :show, :create] do
    resources :tic_tac_toe_moves, only: [:create], as: :moves
  end

  namespace :onboarding do
    resources :developer_informations, only: %i[new create]
    resources :developer_skills, only: %i[new create]
    resources :developer_preferences, only: %i[new create]
  end

  resources :developers, only: %i[show]
  resources :commands, only: %i[index]
  resources :places, only: %i[index create]
  resources :todos, only: %i[index update]
  resources :coffee_prompts, only: %i[new create]

  get 'tabs', to: 'pages#tabs'
  get 'profile_tab', to: 'pages#profile_tab'
  get 'personal_info_tab', to: 'pages#personal_info_tab'
  get 'notifications_tab', to: 'pages#notifications_tab'

  resources :posts, only: %i[new create edit update show]
  resources :slow_characters, only: %i[index]

  resources :profiles, only: %i[index]

  resources :pizzas, only: %i[index]
  resources :toppings, only: %i[index]

  resources :kanban_boards, only: %i[show]
  resources :kanban_columns, only: %i[update]
  resources :kanban_cards, only: %i[update]
  
  resources :users, only: %i[show]
  resources :follows, only: %i[create]
  
  resources :emails, only: %i[index]
  namespace :emails do
    resource :bulk, only: :destroy, controller: :bulk
  end

  resources :comments, only: %i[index new create show] do
    resources :replies, only: %i[new create]
  end

  resources :events, only: %i[index new create]
  resources :pets, only: %i[new create index]
end

app/models/character.rb
class Character < ApplicationRecord
  scope :by_name, -> (name) { where('name ILIKE ?', "%#{name}%") }
  scope :by_species, -> (species) { where species: species }
  scope :by_homeworld, -> (homeworld) { where homeworld: homeworld }
  scope :by_affiliation, -> (affiliation) { where affiliation: affiliation }

  def self.search(params)
    characters = where(nil)

    characters = characters.by_name(params[:name]) if params[:name].present?
    characters = characters.by_species(params[:species]) if params[:species].present?
    characters = characters.by_homeworld(params[:homeworlds]) if params[:homeworlds].present?
    characters = characters.by_affiliation(params[:affiliations]) if params[:affiliations].present?

    characters
  end
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/command.rb
class Command < ApplicationRecord
  scope :by_name, -> (query) { where("name LIKE ?", "%#{query}%") }

  def self.search(params)
    commands = where(nil)
    commands = commands.by_name(params[:query])
    commands
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :parent, class_name: "Comment", optional: true
  has_many :replies, foreign_key: "parent_id", class_name: "Comment", dependent: :destroy

  default_scope { order(created_at: :desc) }
  scope :top_level, -> { where(parent_id: nil) }
end

app/models/developer.rb
class Developer < ApplicationRecord
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  default_scope { order(starting_at: :asc) }
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :followed_user, class_name: 'User'
  belongs_to :follower, class_name: 'User'

  after_create_commit :send_notification

  private

  def send_notification
    NewFollowerNotification.with(follow: self).deliver_later(followed_user)
  end
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :specializations

  accepts_nested_attributes_for :specializations, allow_destroy: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  has_rich_text :content

  after_create_commit {
    broadcast_append_to "chatroom_#{chatroom.id}",
      target: "messages",
      partial: 'messages/message'
  }
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_one_attached :photo
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  has_many :pizza_toppings
  has_many :toppings, through: :pizza_toppings

  def topping_names
    toppings.map(&:name).join(', ').titleize
  end
end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def as_marker
    { lat: latitude, lng: longitude }
  end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :job
  belongs_to :specialization
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank
end

app/models/todo.rb
class Todo < ApplicationRecord
  scope :completed, -> { where(completed: true) }
  scope :incomplete, -> { where(completed: false) }
end

app/models/topping.rb
class Topping < ApplicationRecord
  has_many :pizza_toppings
  has_many :pizzas, through: :pizza_toppings

  scope :filter_by_name, -> (name) { where("name ILIKE ?", "%#{name}%") }

  def self.search(params)
    toppings = all
    toppings = toppings.filter_by_name(params[:name]) if params[:name].present?

    toppings
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :messages, dependent: :destroy
  has_many :tic_tac_toe_games, dependent: :destroy
  has_many :tic_tac_toe_moves, dependent: :destroy

  has_many :notifications, as: :recipient, dependent: :destroy

  has_many :followees, foreign_key: :follower_id, class_name: "Follow", dependent: :destroy
  has_many :followed_users, through: :followees

  has_many :following_users, foreign_key: :followed_user_id, class_name: "Follow", dependent: :destroy
  has_many :followers, through: :following_users

  def self.online
    ids = ActionCable.server.pubsub.redis_connection_for_subscriptions.smembers("online_users")
    where(id: ids)
  end

  def broadcast_online
    broadcast_append_to "online_users", target: "online_users",
      partial: 'users/card',
      locals: { user: self }
  end

  def broadcast_offline
    broadcast_remove_to "online_users", target: "user_#{id}"
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_command_palette.html.erb
<div class="relative z-10 hidden" data-command-palette-target="palette" role="dialog" aria-modal="true">
  <div class="fixed inset-0 bg-gray-900 bg-opacity-40 transition-opacity"></div>

  <div class="fixed inset-0 z-10 overflow-y-auto p-4 sm:p-6 md:p-20">
    <div class="mx-auto max-w-xl transform divide-y divide-gray-100 overflow-hidden rounded-xl bg-white shadow-2xl ring-1 ring-black ring-opacity-5 transition-all">
      <%= form_tag commands_path, class: "relative", method: :get, data: {controller: "autosubmit", turbo_frame: "commands"} do %>
        <svg class="pointer-events-none absolute top-3.5 left-4 h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clip-rule="evenodd" />
        </svg>
        <input
          name="query"
          data-command-palette-target="input"
          data-action="input->autosubmit#debouncedSubmit"
          type="text"
          class="h-12 w-full border-0 bg-transparent pl-11 pr-4 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm" placeholder="Search..." role="combobox" aria-expanded="false" aria-controls="options">
      <% end %>

      <%= turbo_frame_tag "commands", src: commands_path %>
    </div>
  </div>
</div>

app/views/shared/_divider.html.erb
<div class="relative">
  <div class="absolute inset-0 flex items-center" aria-hidden="true">
    <div class="w-full border-t border-gray-300"></div>
  </div>
  <div class="relative flex justify-center">
    <span class="bg-white px-3 text-lg font-medium text-gray-900"><%= title %></span>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div
    class="max-w-sm w-full bg-white shadow-lg rounded-lg pointer-events-auto overflow-hidden fixed top-5 right-5"
    data-controller="flash">
    <div class="p-4">
      <div class="flex items-start">
        <div class="flex-shrink-0">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </div>

        <div class="ml-3 w-0 flex-1 pt-0.5">
          <span class="text-sm text-gray-700 leading-5 font-medium">
            <%= value %>
          </span>
        </div>

        <div class="ml-4 flex-shrink-0 flex">
          <button
            class="bg-white rounded-md inline-flex text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            data-action="flash#close">
            <span class="sr-only">Close</span>
            <!-- Heroicon name: solid/x -->
            <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_tabs.html.erb
<div>
  <div class="hidden sm:block">
    <div class="border-b border-gray-200">
      <nav class="-mb-px flex space-x-8" aria-label="Tabs">
        <%= nav_link_to "Profile", profile_tab_path,
          active_class: "border-indigo-500 text-indigo-600",
          class: "whitespace-nowrap border-b-2 py-4 px-1 text-sm font-medium" %>
        <%= nav_link_to "Personal Information", personal_info_tab_path,
          active_class: "border-indigo-500 text-indigo-600",
          class: "whitespace-nowrap border-b-2 py-4 px-1 text-sm font-medium" %>
        <%= nav_link_to "Notifications", notifications_tab_path,
          active_class: "border-indigo-500 text-indigo-600",
          class: "whitespace-nowrap border-b-2 py-4 px-1 text-sm font-medium" %>
      </nav>
    </div>
  </div>
</div>

app/views/shared/_turbo_destroy_dialog.html.erb
<dialog data-turbo-confirm-target="dialog">
  <div data-form="destroy" class="animated fadeIn fixed inset-0 overflow-y-auto flex items-center justify-center">
    <!-- Modal Inner Container -->
    <form method="dialog" class="max-h-screen w-full max-w-lg relative flex justify-center">
      <!-- Modal Card -->
      <div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full sm:p-6">
        <div class="sm:flex sm:items-start">
          <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
            <!-- Heroicon name: outline/exclamation -->
            <svg class="h-6 w-6 text-red-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
          </div>
          <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
            <h3 class="text-lg leading-6 font-medium text-gray-900" data-turbo-confirm-target="title">
            </h3>
            <div class="mt-2">
              <p class="text-sm text-gray-500" data-turbo-confirm-target="body">
              </p>
            </div>
          </div>
        </div>
        <div class="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse">
          <button data-turbo-confirm-target="confirmButton" value="confirm" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm">
          </button>
          <button data-turbo-confirm-target="cancelButton" value="cancel" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:w-auto sm:text-sm">
          </button>
        </div>
      </div>
    </form>
  </div>
</dialog>