config/routes.rb
Rails.application.routes.draw do
  root 'pages#kitchensink'
  
  resources :tweets
  devise_for :users
  
  get 'multiple_select', to: 'pages#multiple_select'
  get 'online_users', to: 'pages#online_users'
  get 'modal', to: 'pages#modal'
  get 'landing_page', to: 'pages#landing_page'
  post 'track_event', to: 'pages#track_event'
  
  resources :technologies, only: [:create]
  resources :favourite_technologies, only: [:create, :destroy]

  resources :recipes, except: [:destroy]
  resources :ingredients, only: [:destroy]
  resources :nested_ingredients, only: [:new, :destroy]
  resources :characters, only: [:index, :destroy]

  resources :chatrooms, only: [:index, :show] do 
    resources :messages, only: [:create]
  end

  resources :tic_tac_toe_games, only: [:index, :show, :create] do
    resources :tic_tac_toe_moves, only: [:create], as: :moves
  end

  namespace :onboarding do
    resources :developer_informations, only: %i[new create]
    resources :developer_skills, only: %i[new create]
    resources :developer_preferences, only: %i[new create]
  end

  resources :developers, only: %i[show]
  resources :commands, only: %i[index]
  resources :places, only: %i[index create]
  resources :todos, only: %i[index update]
  resources :coffee_prompts, only: %i[new create]

  get 'tabs', to: 'pages#tabs'
  get 'profile_tab', to: 'pages#profile_tab'
  get 'personal_info_tab', to: 'pages#personal_info_tab'
  get 'notifications_tab', to: 'pages#notifications_tab'

  resources :posts, only: %i[new create edit update show]
  resources :slow_characters, only: %i[index]

  resources :profiles, only: %i[index]

  resources :pizzas, only: %i[index]
  resources :toppings, only: %i[index]

  resources :kanban_boards, only: %i[show]
  resources :kanban_columns, only: %i[update]
  resources :kanban_cards, only: %i[update]
  
  resources :users, only: %i[show]
  resources :follows, only: %i[create]
  
  resources :emails, only: %i[index]
  namespace :emails do
    resource :bulk, only: :destroy, controller: :bulk
  end

  resources :comments, only: %i[index new create show] do
    resources :replies, only: %i[new create]
  end

  resources :events, only: %i[index new create]
  resources :pets, only: %i[new create index]
end

app/models/character.rb
class Character < ApplicationRecord
  scope :by_name, -> (name) { where('name ILIKE ?', "%#{name}%") }
  scope :by_species, -> (species) { where species: species }
  scope :by_homeworld, -> (homeworld) { where homeworld: homeworld }
  scope :by_affiliation, -> (affiliation) { where affiliation: affiliation }

  def self.search(params)
    characters = where(nil)

    characters = characters.by_name(params[:name]) if params[:name].present?
    characters = characters.by_species(params[:species]) if params[:species].present?
    characters = characters.by_homeworld(params[:homeworlds]) if params[:homeworlds].present?
    characters = characters.by_affiliation(params[:affiliations]) if params[:affiliations].present?

    characters
  end
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/command.rb
class Command < ApplicationRecord
  scope :by_name, -> (query) { where("name LIKE ?", "%#{query}%") }

  def self.search(params)
    commands = where(nil)
    commands = commands.by_name(params[:query])
    commands
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :parent, class_name: "Comment", optional: true
  has_many :replies, foreign_key: "parent_id", class_name: "Comment", dependent: :destroy

  default_scope { order(created_at: :desc) }
  scope :top_level, -> { where(parent_id: nil) }
end

app/models/developer.rb
class Developer < ApplicationRecord
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  default_scope { order(starting_at: :asc) }
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :followed_user, class_name: 'User'
  belongs_to :follower, class_name: 'User'

  after_create_commit :send_notification

  private

  def send_notification
    NewFollowerNotification.with(follow: self).deliver_later(followed_user)
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :specializations

  accepts_nested_attributes_for :specializations, allow_destroy: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  has_rich_text :content

  after_create_commit {
    broadcast_append_to "chatroom_#{chatroom.id}",
      target: "messages",
      partial: 'messages/message'
  }
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_one_attached :photo
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  has_many :pizza_toppings
  has_many :toppings, through: :pizza_toppings

  def topping_names
    toppings.map(&:name).join(', ').titleize
  end
end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def as_marker
    { lat: latitude, lng: longitude }
  end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :job
  belongs_to :specialization
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank
end

app/models/todo.rb
class Todo < ApplicationRecord
  scope :completed, -> { where(completed: true) }
  scope :incomplete, -> { where(completed: false) }
end

app/models/topping.rb
class Topping < ApplicationRecord
  has_many :pizza_toppings
  has_many :pizzas, through: :pizza_toppings

  scope :filter_by_name, -> (name) { where("name ILIKE ?", "%#{name}%") }

  def self.search(params)
    toppings = all
    toppings = toppings.filter_by_name(params[:name]) if params[:name].present?

    toppings
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :messages, dependent: :destroy
  has_many :tic_tac_toe_games, dependent: :destroy
  has_many :tic_tac_toe_moves, dependent: :destroy

  has_many :notifications, as: :recipient, dependent: :destroy

  has_many :followees, foreign_key: :follower_id, class_name: "Follow", dependent: :destroy
  has_many :followed_users, through: :followees

  has_many :following_users, foreign_key: :followed_user_id, class_name: "Follow", dependent: :destroy
  has_many :followers, through: :following_users

  def self.online
    ids = ActionCable.server.pubsub.redis_connection_for_subscriptions.smembers("online_users")
    where(id: ids)
  end

  def broadcast_online
    broadcast_append_to "online_users", target: "online_users",
      partial: 'users/card',
      locals: { user: self }
  end

  def broadcast_offline
    broadcast_remove_to "online_users", target: "user_#{id}"
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  include Pagy::Backend
  def index
    @pagy, @characters = pagy(Character.search(params), items: 5)

    @species = Character.pluck(:species).uniq
    @homeworlds = Character.pluck(:homeworld).uniq
    @affiliations = Character.pluck(:affiliation).uniq
  end

  def destroy
    @character = Character.find(params[:id])

    respond_to do |format|
      if @character.destroy
        flash.now[:notice] = "Character was successfully deleted"
        format.turbo_stream
      end
    end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@character) %>
<%= turbo_stream.update "flash", partial: "shared/flash" %>

app/views/characters/index.html.erb
<%= turbo_frame_tag "characters", class: "w-full" do %>
  <div class="px-4 sm:px-6 lg:px-8 py-8">
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-base font-semibold leading-6 text-gray-900">Star wars characters 🛸</h1>
      </div>
    </div>
    
    <div class="flex flex-col space-y-8 my-8">
      <%= form_with url: characters_path,
        method: :get,
        class: 'flex space-x-10',
        data: {controller: 'autosubmit', turbo_frame: 'characters_table'} do |f| %>
        <div class="flex flex-col">
          <div>
            <%= f.text_field "name",
              placeholder: "Search through the galaxy",
              value: params[:name],
              data: {action: "input->autosubmit#debouncedSubmit"},
              class: "border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none w-[320px] focus:ring-orange focus:border-orange sm:text-sm" %>
          </div>

          <div class="flex space-x-5 mt-8">
            <div class="relative" data-controller="dropdown">
                <!-- Expand/collapse question button -->
              <button data-action="click->dropdown#toggle click@window->dropdown#hide" data-dropdown-target="button" type="button" class="group inline-flex items-center justify-center text-sm font-medium text-gray-700 hover:text-gray-900" aria-controls="filter-section-1" aria-expanded="false">
                <span class="font-medium text-gray-900 text-base"> Species </span>
                <svg class="flex-shrink-0 -mr-1 ml-1 h-5 w-5 text-gray-400 group-hover:text-gray-500" x-description="Heroicon name: solid/chevron-down" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </button>
              <div class="py-6 absolute left-0 max-h-64 overflow-auto mt-2 hidden bg-white z-200 min-w-full rounded-md shadow-2xl" data-dropdown-target="menu">
                <div class="space-y-6 pl-4">
                  <% @species.each do |specie| %>
                    <label class="flex items-center justify-start mr-4 cursor-pointer">
                      <%= f.check_box('species[]', {data: {action: 'autosubmit#submit' }, checked: params[:species]&.include?(specie.to_s), class: 'h-4 w-4 border-gray-300 rounded text-indigo-600 focus:ring-indigo-500'}, specie, nil) %>
                      <span class="ml-3 text-sm text-gray-700 flex-nowrap whitespace-nowrap" data-action="click->join-classes#checkAdjacentFilter click->auto-submit#submit"><%= specie.to_s.gsub('_', ' ').capitalize %></span>
                    </label>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="relative" data-controller="dropdown">
                <!-- Expand/collapse question button -->
              <button data-action="click->dropdown#toggle click@window->dropdown#hide" data-dropdown-target="button" type="button" class="group inline-flex items-center justify-center text-sm font-medium text-gray-700 hover:text-gray-900" aria-controls="filter-section-1" aria-expanded="false">
                <span class="font-medium text-gray-900 text-base"> Home World </span>
                <svg class="flex-shrink-0 -mr-1 ml-1 h-5 w-5 text-gray-400 group-hover:text-gray-500" x-description="Heroicon name: solid/chevron-down" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </button>
              <div class="py-6 absolute left-0 max-h-64 overflow-auto mt-2 hidden bg-white z-200 min-w-full rounded-md shadow-2xl" data-dropdown-target="menu">
                <div class="space-y-6 pl-4">
                  <% @homeworlds.each do |homeworld| %>
                    <label class="flex items-center justify-start mr-4 cursor-pointer">
                      <%= f.check_box('homeworlds[]', {data: {action: 'autosubmit#submit', 'form-target': 'checkbox'}, checked: params[:homeworlds]&.include?(homeworld.to_s), class: 'h-4 w-4 border-gray-300 rounded text-indigo-600 focus:ring-indigo-500'}, homeworld, nil) %>
                      <span class="ml-3 text-sm text-gray-700 flex-nowrap whitespace-nowrap" data-action="click->join-classes#checkAdjacentFilter click->auto-submit#submit"><%= homeworld.to_s.gsub('_', ' ').capitalize %></span>
                    </label>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="relative" data-controller="dropdown">
              <!-- Expand/collapse question button -->
              <button data-action="click->dropdown#toggle click@window->dropdown#hide" data-dropdown-target="button" type="button" class="group inline-flex items-center justify-center text-sm font-medium text-gray-700 hover:text-gray-900" aria-controls="filter-section-1" aria-expanded="false">
                <span class="font-medium text-gray-900 text-base"> Affiliation </span>
                <svg class="flex-shrink-0 -mr-1 ml-1 h-5 w-5 text-gray-400 group-hover:text-gray-500" x-description="Heroicon name: solid/chevron-down" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </button>
              <div class="py-6 absolute left-0 max-h-64 overflow-auto mt-2 hidden bg-white z-200 min-w-full rounded-md shadow-2xl" data-dropdown-target="menu">
                <div class="space-y-6 pl-4">
                  <% @affiliations.each do |affiliation| %>
                    <label class="flex items-center justify-start mr-4 cursor-pointer">
                      <%= f.check_box('affiliations[]', {data: {action: 'autosubmit#submit', 'form-target': 'checkbox'}, checked: params[:affiliations]&.include?(affiliation.to_s), class: 'h-4 w-4 border-gray-300 rounded text-indigo-600 focus:ring-indigo-500'}, affiliation, nil) %>
                      <span class="ml-3 text-sm text-gray-700 flex-nowrap whitespace-nowrap" data-action="click->join-classes#checkAdjacentFilter click->auto-submit#submit"><%= affiliation.to_s.gsub('_', ' ').capitalize %></span>
                    </label>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="relative flex items-center" data-controller="loading">
              <%= link_to "Clear", characters_path, class: 'text-gray-500 text-xs', data: { turbo_frame: 'characters' } %>
              <svg class="hidden absolute animate-spin -mr-6 right-0 h-3 w-3" data-form-target="spinner" data-loading-target="spinner" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <%= turbo_frame_tag "characters_table" do %>
      <div class="flow-root">
        <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
            <table class="min-w-full divide-y divide-gray-300">
              <thead>
                <tr>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Image</th>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Name</th>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Species</th>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Homeworld</th>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Affiliation</th>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Actions</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200">
                <% @characters.each do |character| %>
                  <tr id="<%= dom_id(character) %>">
                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
                      <img class="inline-block h-14 w-14 rounded-md object-cover" src="<%= character.image_url %>" alt="">
                    </td>
                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
                      <%= character.name %>
                    </td>
                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
                      <%= character.species %>
                    </td>
                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
                      <%= character.homeworld %>
                    </td>
                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
                      <%= character.affiliation %>
                    </td>
                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
                      <%= button_to character_path(character),
                        method: :delete,
                        form: {
                          data: {
                            turbo_confirm: "true",
                            confirm_body: "The world may implode if you continue."
                          }
                        } do %>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                        </svg>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>